### ISSUE TITLE
XML parser 

### ISSUE THREAD

**Issue by StarterEventPlatform** [StarterEventPlatform/Platform#1]
Create xml parser and creator.

First of all, we should create abstract parser for this goal.

**Comment by GlebDurygin** [comment]
class XmlParser
- Node getNode(String tagName, NodeList nodes)
- Node getNode(String tagName)
- NodeList getElementsByTagName(String name)
- Sting getNodeValue(Node node)
- String getNodeValue(String tagName, NodeList nodes)
- String getNodeValue(String tagName)
- String getNodeAttribute(String attributeName, Node node)
- String getNodeAttribute(String tagName, String attributeName, NodeList nodes)
- NamedNodeMap getAttributes(Node node)
- NodeList getRoot()
- NodeList getChildNotes(Node node)
- NodeList getChildNotes(String tagName)

**Comment by GlebDurygin** [comment]
Добавлять аннотации к классам, которые будут заворачиваться в xml, для правильной работы парсера.
https://github.com/FasterXML/jackson-dataformat-xml/wiki/Jackson-XML-annotations
