### ISSUE TITLE
Research: MongoDB

### ISSUE THREAD

**Issue by NikitaDestrain** [StarterEventPlatform/Platform#10]

**Comment by GlebDurygin** [comment]
1) download and install MongoDB
https://docs.mongodb.com/manual/tutorial/install-mongodb-on-windows/
2) run MongoDB\Server\4.0\bin\mongod.exe

**Comment by GlebDurygin** [comment]
3) IDEA
File -> Settings -> Plugins -> Browse repositories -> Mongo Plugin
