### ISSUE TITLE
Controller

### ISSUE THREAD

**Issue by StarterEventPlatform** [StarterEventPlatform/Platform#18]
Realization.

**Comment by GlebDurygin** [comment]
Add userController a74fcd19575ddd257841041c292325b0306c74e4 by [Nikita Govokhin](https://github.com/NikitaDestrain)
Add geoPositionController 7d43b3c3012b095d21926875f33b86ebb30479f7

**Comment by NikitaDestrain** [comment]
All controllers was implemented. 

Wait the next issue "new features for controller"
