### ISSUE TITLE
Bug: XmlParser can not return valid sub map

### ISSUE THREAD

**Issue by NikitaDestrain** [StarterEventPlatform/Platform#21]
Был замечен следующий баг: 
1. Передаем Maintainer, который содержит User
2. Парсим с помощью XmlParser - getParsedXml
3. Мапа получается невалидная, так как все данные юзера слепились и невозможно их распарсить.

P.S. Скрин, если достать юзера из мапы maintainer'a
![bug](https://user-images.githubusercontent.com/33430830/48312210-afc3de00-e5c4-11e8-9011-c1d1e0e4239c.PNG)

**Comment by GlebDurygin** [comment]
fix bug 28defa9865f7b4ddfdeb5a4e111959c2bf34b5b2
