### ISSUE TITLE
Research: EntityContainer vs Container<T> interface

### ISSUE THREAD

**Issue by NikitaDestrain** [StarterEventPlatform/Platform#22]
We should choose type of container. Cuz each of the type has advantages and disadvantages.

**Comment by GlebDurygin** [comment]
1) 9304c1b8e75a1e737a1fa284a9611b0a53c863f7 by [Nikita Govokhin](https://github.com/NikitaDestrain)
2) 36fc022660e7ef4a3c011fc8f8c46967452e320d by [Gleb Durygin](https://github.com/GlebDurygin)
