### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by StarterEventPlatform** [StarterEventPlatform/Platform#4]
We should create model (POJO).

And try to create xml, json sample for it.

**Comment by NikitaDestrain** [comment]
Status:

1. [User](https://github.com/StarterEventPlatform/Platform/blob/develop/platform/src/main/java/com/eventplatform/model/User.java)
2. [ GeoPosition](https://github.com/StarterEventPlatform/Platform/blob/develop/platform/src/main/java/com/eventplatform/model/GeoPosition.java)
3. [Event](https://github.com/StarterEventPlatform/Platform/blob/develop/platform/src/main/java/com/eventplatform/model/Event.java)
4. [Maintainer](https://github.com/StarterEventPlatform/Platform/blob/develop/platform/src/main/java/com/eventplatform/model/Maintainer.java)
5. [Entity](https://github.com/StarterEventPlatform/Platform/blob/develop/platform/src/main/java/com/eventplatform/model/Entity.java)

**Comment by NikitaDestrain** [comment]
Добавлена реализация для некоторых классов.
