### ISSUE TITLE
Factory

### ISSUE THREAD

**Issue by NikitaDestrain** [StarterEventPlatform/Platform#8]
Create factory for all pojo

**Comment by NikitaDestrain** [comment]
Status: 

1. [UserFactory](https://github.com/StarterEventPlatform/Platform/blob/develop/platform/src/main/java/com/eventplatform/factory/UserFactory.java)

**Comment by NikitaDestrain** [comment]
Добавлены тесты для [UserFactory](https://github.com/StarterEventPlatform/Platform/blob/develop/platform/src/test/java/UserFactoryTest.java).

**Comment by GlebDurygin** [comment]
Add test for factories fe5ed2b3afb91baf89c1549763c8ef4beac5ddd6
